sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: bqsVn2B1acWhS4D7iwnuzprMIKl8TjvrOy6G+wzhcBvJKoFWpcXxTY+XWczAbgW/A5TJMEk6blNm/5IwSeU6N9G8hI5EXxBPXA6pVGblQgfyt7nB/N7RKLSCIaYJ0Jnl1VslUDuvPMefZPOTzGZQt+iPJUUQUYqzBjx+Aj+33/C4qBKrtLhcHolr1uSJ3zzceM5NgFByN+dfYnQV2k/J6iROcpz2hcomLNE7ykmtPc4oWtwdHYxCs7TfMKhPR3xWeGW/lasi1m+JSO1fwO9KjrLcaImXm0fPx0dWbNsMdneEuE/eRzlH1p9dW5MyrQf0ru21DVpOFE45hTkkSxUZEhukg/d8eLfIiXXU600VXTtwdhIfUfXGD8TwayfNGTJT6B/jNyl6Wzoo3vih5yLIdXT/JVC30eqLMRduliOUCvC3Eow0nGbxApZ2/NDyAsTIGuj8OTXiqrtxyJi0+Vi9A5lE52kDTUjQ20O1MzlOHxneOoIsMRGN1XhUuxttWENYE96HVnt8PMZkL43e2OUOHDZ7witMslz7ayjnkH/tuNbUNT5r8bCkFTekXA9X58mQ68jIiOSNwjsdfOu/gTHwzHuVChdCsJkjRhqOu8Z3gCO7tzk9yIrNcUrBjvlRnM3BJPs21GtCbA9824UFenHBmjHGbDUzFt1dfEV4H1lzp+I=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Joshua-Volume-5_5471
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy